FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    python3 make g++ bash git curl procps \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash sandbox
RUN mkdir -p /home/sandbox/app /home/sandbox/workspace

RUN chown -R sandbox:sandbox /home/sandbox/app /home/sandbox/workspace

USER sandbox
WORKDIR /home/sandbox/app

COPY --chown=sandbox:sandbox package*.json ./
RUN npm install
COPY --chown=sandbox:sandbox . .
RUN npm run build

ENV HOME=/home/sandbox/workspace
ENV TERM=xterm-256color
ENV NODE_ENV=production
EXPOSE 8080

CMD ["npm", "run", "start:fly"]