app = "plinth"
primary_region = "yyz"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 20
    soft_limit = 15

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/health"
    grace_period = "5s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024